{{- if .Values.openWebUI.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foundry-local.fullname" . }}-openwebui-config
  namespace: {{ include "foundry-local.namespace" . }}
  labels:
    {{- include "foundry-local.labels" . | nindent 4 }}
    app.kubernetes.io/component: open-webui
data:
  # Open WebUI configuration
  WEBUI_NAME: {{ .Values.openWebUI.config.webuiName | quote }}
  WEBUI_URL: {{ .Values.openWebUI.config.webuiUrl | quote }}
  WEBUI_SECRET_KEY: {{ .Values.openWebUI.config.webuiSecretKey | quote }}
  
  # OpenAI API configuration - connect to Foundry service
  OPENAI_API_BASE_URL: "http://{{ include "foundry-local.foundry.serviceName" . }}.{{ include "foundry-local.namespace" . }}.svc.cluster.local:{{ .Values.foundry.service.port }}/v1"
  OPENAI_API_KEY: "not-needed"
  
  # Default model configuration
  DEFAULT_MODELS: {{ if .Values.openWebUI.config.defaultModels }}{{ .Values.openWebUI.config.defaultModels | quote }}{{ else }}{{ .Values.foundry.model | quote }}{{ end }}
  
  # UI customization
  DEFAULT_USER_ROLE: {{ .Values.openWebUI.config.defaultUserRole | quote }}
  ENABLE_SIGNUP: {{ .Values.openWebUI.config.enableSignup | quote }}
  ENABLE_LOGIN_FORM: {{ .Values.openWebUI.config.enableLoginForm | quote }}
  ENABLE_COMMUNITY_SHARING: {{ .Values.openWebUI.config.enableCommunitySharing | quote }}
  
  # Performance settings
  CHUNK_SIZE: {{ .Values.openWebUI.config.chunkSize | quote }}
  CHUNK_OVERLAP: {{ .Values.openWebUI.config.chunkOverlap | quote }}
  
  {{- range .Values.openWebUI.extraEnvVars }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
{{- end }}