---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foundry-gpu-oras
  namespace: foundry-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/foundry-gpu-oras/chart
      sourceRef:
        kind: GitRepository
        name: foundry-gitops
        namespace: foundry-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: foundry-values
      optional: true
  values:
    # Global registry override for foundryoci
    global:
      imageRegistry: "foundryoci.azurecr.io"
    
    # GPU-ORAS deployment configuration
    foundry:
      enabled: true
      deploymentType: "gpu-oras"
      
      # BYO models configuration
      byo:
        enabled: true
        registry: foundryoci.azurecr.io
        repository: byo-models-gpu/llama-3.2-1b-cuda
        tag: v1.0.0 # {"$imagepolicy": "flux-system:foundry-local-olive-models:tag"}
      
      # Image configuration (uses global.imageRegistry)
      images:
        gpu-oras:
          repository: foundry-local-gpu-oras
          tag: "latest"
      
      # GPU resource requirements
      resources:
        requests:
          nvidia.com/gpu: 1
        limits:
          nvidia.com/gpu: 1
  
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
