{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "foundry-local.fullname" . }}
  namespace: {{ include "foundry-local.namespace" . }}
  labels:
    {{- include "foundry-local.labels" . | nindent 4 }}
    {{- with .Values.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "foundry-local.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: foundry-local
  endpoints:
    - port: http
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.interval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
      {{- with .Values.monitoring.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.monitoring.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.openWebUI.enabled }}
    - port: webui-http
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
  {{- end }}
{{- end }}